### ISSUE TITLE
ExtendedBuild

### ISSUE THREAD

**Issue by Fale** [openshift/golang-ex#21]
It would probably better to move to ExtendedBuild, as suggested in the doc for golang: https://docs.openshift.com/container-platform/3.5/dev_guide/builds/build_strategies.html#extended-builds

**Comment by chlunde** [comment]
This might only be 50% relevant for this issue, but I didn't find any examples of rolling your own s2i runtime and builder images from within OpenShift and using extended builds. This example probably contains some artifacts from me not understanding s2i properly, and because I wrote *everything* inside embedded Dockerfiles, which has its pros and cons...

## Builder image
```yaml
apiVersion: v1
kind: BuildConfig
metadata:
  name: golang-builder
spec:
  output:
    to:
      kind: ImageStreamTag
      name: golang-builder:latest
  source:
    dockerfile: |-
      FROM registry.access.redhat.com/rhel7:latest
      RUN curl -O https://storage.googleapis.com/golang/go1.9rc2.linux-amd64.tar.gz && tar -C /usr/local -xzf go1.9rc2.linux-amd64.tar.gz && rm go1.9rc2.linux-amd64.tar.gz
      RUN yum -y install git && \
       yum clean all
      ENV GOROOT=/usr/local/go
      ENV GOPATH=/tmp/gopath
      RUN echo 'user:x:1001:0:User:/tmp:/bin/bash' >> /etc/passwd
      RUN mkdir -p /opt/app-root && chgrp 0 /opt/app-root && chmod g+w /opt/app-root && \
          echo 'export PATH=/usr/local/go/bin:$PATH; echo "Assemble"; set -x; mkdir -p $GOPATH/src/$(dirname $GOPKG); ln -s /tmp/src $GOPATH/src/$GOPKG; cd $GOPATH/src/$GOPKG; go get -v . && go build -v -o /opt/app-root/main' > /usr/local/bin/assemble && \
          chmod +x /usr/local/bin/assemble

      LABEL io.k8s.description="RHEL7 based image with Go compiler for building Go based apps" \
        io.openshift.s2i.scripts-url=image:///usr/local/bin/ \
        io.openshift.s2i.assemble-input-files=/opt/app-root
      USER 1001
    type: Dockerfile
  strategy:
    type: Docker
```
## Runtime image
```yaml
apiVersion: v1
kind: BuildConfig
metadata:
  name: rhel7-runtime
spec:
  output:
    to:
      kind: ImageStreamTag
      name: rhel7-runtime:latest
  source:
    dockerfile: |-
      FROM registry.access.redhat.com/rhel7:latest
      LABEL io.k8s.description="RHEL7 based image for running applications"

      # This will copy /opt/app-root from the build into $WORKDIR/app-root, i.e /opt/app-root, in the final container
      LABEL io.openshift.s2i.assemble-input-files="/opt/app-root/:."
      WORKDIR /opt/

      RUN mkdir -p /opt/app-root && \
          chgrp 0 /opt/app-root && \
          chmod g+w /opt/app-root && \
          echo 'set -x; find /opt/ -ls' > /usr/local/bin/assemble-runtime && \
          chmod +x /usr/local/bin/assemble-runtime
      RUN echo -e '#!/bin/sh\nexec /opt/app-root/main' > /usr/local/bin/run && chmod +x /usr/local/bin/run

      LABEL io.openshift.s2i.scripts-url=image:///usr/local/bin/
      USER 1001
    type: Dockerfile
  strategy:
    type: Docker
```

## Building your app
```yaml
apiVersion: v1
kind: BuildConfig
metadata:
  name: your-app
spec:
  output:
    to:
      kind: ImageStreamTag
      name: your-app:latest
  source:
    git:
      ref: master
      uri: YOUR_GIT_URL
    sourceSecret:
      name: YOUR_GIT_SECRET_KEY
    type: Git
  strategy:
    sourceStrategy:
      env:
      - name: GOPKG
        value: github.com/user/your-app
      from:
        kind: ImageStreamTag
        name: golang-builder:latest
      runtimeImage:
        kind: ImageStreamTag
        name: rhel7-runtime:latest
    type: Source
```
